;; -*- mode: eask; lexical-binding: t -*-

(package "ansi-colorful"
         "0.1.0"
         "Toggle render ansi-color")

(website-url "https://github.com/jcs-elpa/ansi-colorful")
(keywords "faces")

(package-file "ansi-colorful.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
